CREATE TABLE IF NOT EXISTS Post_new (
  PostID INTEGER PRIMARY KEY AUTOINCREMENT,
  UserID INTEGER,
  Content TEXT,
  ImageURL VARCHAR(255),
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  PrivacySetting VARCHAR(255),
  AllowedViewers TEXT,
  GroupID INTEGER,
  FOREIGN KEY (UserID) REFERENCES User(UserID)
  FOREIGN KEY (GroupID) REFERENCES Cluster(GroupID)
);

ALTER TABLE Post RENAME TO Post_Old;
ALTER TABLE Post_New RENAME TO Post;

DROP TABLE Post_Old;
