CREATE TABLE IF NOT EXISTS GroupChatMessage (
  MessageID VARCHAR(36) PRIMARY KEY,
  GroupID INTEGER,
  SenderUserID INTEGER,
  Content TEXT,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  RoomID VARCHAR(36),
  FOREIGN KEY (GroupID) REFERENCES Cluster(GroupID),
  FOREIGN KEY (SenderUserID) REFERENCES User(UserID),
  FOREIGN KEY (RoomID) REFERENCES GroupChatRoom(RoomID)
);