CREATE TABLE IF NOT EXISTS Event (
  EventID INTEGER PRIMARY KEY AUTOINCREMENT,
  GroupID INTEGER NOT NULL,
  Title TEXT NOT NULL,
  Description TEXT,
  EventDateTime DATETIME NOT NULL,
  CreatorID INTEGER NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CreatorID) REFERENCES User(UserID)
  FOREIGN KEY (GroupID) REFERENCES Cluster(GroupID)
);